### PR TITLE
xmas post

### LINKED ISSUE #11: Xmas in Revvie
25/12/2014

### PR DESCRIPTION
**Pull request by martin308**
resolves #11 

@ammeep do you want to add your video to the post somewhere?

### CODE REVIEW

**Comment by ammeep** [comment]
Oh yes! We can upload it to Vimeo?

**Comment by martin308** [comment]
@ammeep did we ever find that sweet video you made?

**Comment by ammeep** [comment]
:( nah I think it got lost



On April 22, 2016 at 3:15:41 PM, Martin Holman (notifications@github.com) wrote:

@ammeep did we ever find that sweet video you made?

**Comment by martin308** [comment]
💩

**Pull request merged**
